package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// Choice is everything the wizard collects. Password is plaintext and is never
// written anywhere — only its hash reaches disk.
type Choice struct {
	Hostname string
	Username string
	Password string
	Github   string
	Disk     string
}

// desktopGroups are the supplemental groups a desktop user needs: seat/input for
// logind and libinput, audio/video/render for PipeWire and DRM, bluetooth for
// BlueZ, docker for rootful docker, admin for sudo. Kept identical to the shell
// installer this replaces.
const desktopGroups = "[admin, audio, video, render, input, bluetooth, seat, docker]"

// RenderCloudConfig produces the Kairos cloud-config the installer drops in /oem
// for `kairos-agent install` to merge. hash is a crypt(3) SHA-512 string.
//
// The ly save.ini stage preseeds the login screen with this user and selects the
// desktop session, so first boot lands on a filled-in login rather than an empty
// one. session_index 2 matches the session ordering in the image.
func RenderCloudConfig(c Choice, hash string) string {
	var b strings.Builder
	b.WriteString("#cloud-config\n")
	b.WriteString("# Generated by the Hadron Desktop installer.\n")
	b.WriteString("install:\n")
	fmt.Fprintf(&b, "  device: %q\n", c.Disk)
	b.WriteString("  auto: true\n")
	b.WriteString("  reboot: true\n")
	fmt.Fprintf(&b, "hostname: %q\n", c.Hostname)
	b.WriteString("users:\n")
	fmt.Fprintf(&b, "  - name: %q\n", c.Username)
	fmt.Fprintf(&b, "    passwd: '%s'\n", hash)
	fmt.Fprintf(&b, "    groups: %s\n", desktopGroups)
	if c.Github != "" {
		b.WriteString("    ssh_authorized_keys:\n")
		fmt.Fprintf(&b, "      - github:%s\n", c.Github)
	}
	b.WriteString("stages:\n")
	b.WriteString("  initramfs:\n")
	b.WriteString("    - name: \"Hadron desktop default session\"\n")
	b.WriteString("      files:\n")
	b.WriteString("        - path: /etc/ly/save.ini\n")
	b.WriteString("          permissions: 0644\n")
	b.WriteString("          content: |\n")
	fmt.Fprintf(&b, "            user = %s\n", c.Username)
	b.WriteString("            session_index = 2\n")
	return b.String()
}

// topLevelKey matches a `users:` or `install:` key at the start of a line,
// allowing leading whitespace — the same shape the shell installer grepped for.
var topLevelKey = regexp.MustCompile(`(?m)^[[:space:]]*(users|install):`)

// ConfigPresent reports whether oemDir already holds an install config other than
// our own output file. If so the caller skips the wizard and installs unattended,
// preserving the shell installer's behaviour for seeded/automated installs.
func ConfigPresent(oemDir, outPath string) (bool, error) {
	var found bool
	for _, pat := range []string{"*.yaml", "*.yml"} {
		matches, err := filepath.Glob(filepath.Join(oemDir, pat))
		if err != nil {
			return false, err
		}
		for _, m := range matches {
			same, err := filepath.Abs(m)
			if err != nil {
				continue
			}
			want, err := filepath.Abs(outPath)
			if err == nil && same == want {
				continue // never count our own output
			}
			data, err := os.ReadFile(m)
			if err != nil {
				continue // unreadable file is not a config we can honour
			}
			if topLevelKey.Match(data) {
				found = true
			}
		}
	}
	return found, nil
}

// HashPassword shells out to openssl for a crypt(3) SHA-512 hash.
//
// Go's stdlib has no crypt(3), and openssl is already in the image. Vendoring a
// SHA-512-crypt implementation would put unaudited crypto in the one code path
// where a mistake locks the user out of their own machine.
func HashPassword(plain string) (string, error) {
	cmd := exec.Command("openssl", "passwd", "-6", "-stdin")
	cmd.Stdin = strings.NewReader(plain)
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("openssl passwd: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}
